en:
  errors:
    faculty_number_taken_by_user: 'is taken by an existing user'
